version: '2.2'
services:
  server1:
    image: jjauzion/elk-single-node
    container_name: server1
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataS1:/home/ubuntu/elasticsearch-7.6.1/data
      - shared_folder:/home/ubuntu/shared_folder
      - ./server1/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./server1/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    ports:
      - 9200:9200
      - 5601:5601
    networks:
      - elastic
  server2:
    image: jjauzion/es-single-node
    container_name: server2
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataS2:/home/ubuntu/elasticsearch-7.6.1/data
      - shared_folder:/home/ubuntu/shared_folder
      - ./server2/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./server2/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    networks:
      - elastic
  server3:
    image: jjauzion/es-single-node
    container_name: server3
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataS3:/home/ubuntu/elasticsearch-7.6.1/data
      - shared_folder:/home/ubuntu/shared_folder
      - ./server3/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./server3/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    networks:
      - elastic
  server4:
    image: jjauzion/es-single-node
    container_name: server4
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataS4:/home/ubuntu/elasticsearch-7.6.1/data
      - shared_folder:/home/ubuntu/shared_folder
      - ./server4/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./server4/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    networks:
      - elastic
  server5:
    image: jjauzion/es-single-node
    container_name: server5
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataS5:/home/ubuntu/elasticsearch-7.6.1/data
      - shared_folder:/home/ubuntu/shared_folder
      - ./server5/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./server5/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    networks:
      - elastic

volumes:
  dataS1:
    driver: local
  dataS2:
    driver: local
  dataS3:
    driver: local
  dataS4:
    driver: local
  dataS5:
    driver: local
  shared_folder:
    driver: local

networks:
  elastic:
    driver: bridge
