version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic
  es01:
    image: jjauzion/es-single-node
    container_name: es01
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - ./es01/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./es01/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: jjauzion/es-single-node
    container_name: es02
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
      - ./es02/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./es02/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    networks:
      - elastic
  es03:
    image: jjauzion/es-single-node
    container_name: es03
    command: tail -f /dev/null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
      - ./es03/elasticsearch.yml:/home/ubuntu/elasticsearch-7.6.1/config/elasticsearch.yml
      - ./es03/jvm.options:/home/ubuntu/elasticsearch-7.6.1/config/jvm.options
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge
